### ISSUE TITLE
Uncertain licensing

### ISSUE THREAD

**Issue by TheProgramableTurtle** [rileytestut/AltServer-Windows#11]
This specific repository doesn’t have a license, but the main AltStore repository does and it is stated in the README AltStore is intended to be an “open source project anyone can use without restrictions”. Is the Windows source also licensed under the Affero GPL?

**Comment by lonkle** [comment]
Yes it is. :)

**Comment by TheProgramableTurtle** [comment]
Thanks, now I can start working on my fork :)

**Comment by lonkelle** [comment]
@TheProgramableTurtle Oh sweet, good luck on your fork. Would you mind telling me what you're planning to add? 😊

**Comment by TheProgramableTurtle** [comment]
@lonkle Sorry, I was just kidding, I can't even remember what I was planning on doing.

**Comment by lonkelle** [comment]
Ha, I got ya. Happens to me all the time actually. #adhd 🙃
