### ISSUE TITLE
Windows 7 support for v1.3. v1.2.2 still works on Windows 7 64 bit.

### ISSUE THREAD

**Issue by badger200** [rileytestut/AltServer-Windows#12]
See title.

Why did you break/drop Windows 7 support after v1.2.2?

Luckily I saved a copy of v1.2.2, I'll attach it to this post for anyone who needs it. Along with the AltServerPatcher I needed to install unc0ver jailbreak onto my device after my jailbreak expired due to revokes.

But much better if we can just continue supporting Windows 7 considering the size of it's current user base.

[AltServerPatcher.zip](https://github.com/rileytestut/AltServer-Windows/files/4819446/AltServerPatcher.zip)
[altinstaller_pretty_sure_this_is_v1.2.2.zip](https://github.com/rileytestut/AltServer-Windows/files/4819447/altinstaller_pretty_sure_this_is_v1.2.2.zip)

**Comment by lonkelle** [comment]
We never actually officially supported Windows 7, it just coincidentally happened to work. None of us have Win 7 machines to test those older builds with. But we accept PRs! :)
