### ISSUE TITLE
SSL Error unable to check ravocation status

### ISSUE THREAD

**Issue by suliveevil** [rileytestut/AltServer-Windows#13]
Is there something wrong with my Windows or my iPadOS?

I'm using Window 10 ver 1909  os-version 18363.900 and iPadOS 14 public beta

![altserver](https://user-images.githubusercontent.com/35763237/85921880-0c673000-b8b2-11ea-813e-84077de6b8ac.png)

**Comment by lonkelle** [comment]
Re-open this if you're still having the issue. :)
