### ISSUE TITLE
Unable to sync over Wi-Fi

### ISSUE THREAD

**Issue by jamesle-0812** [rileytestut/AltServer-Windows#15]
Hi there, I'm using Windows beta 1.4.3 on Windows 10 ver1909 x64. I can refresh apps by connecting my laptop to ipad through cable. However, I can't do it over Wi-Fi. It always shows up "No Connected Devices".
Please help me. Thank you in advance!

**Comment by lonkelle** [comment]
Re-open this issue if you're still running into the same problem. Sounds like a firewall thing to me personally.
