### ISSUE TITLE
Dev beta 2: "The code signature is invalid"

### ISSUE THREAD

**Issue by liroyvh** [rileytestut/AltServer-Windows#16]
Installing apps with AltServer for Windows on iPhones running iOS 14.5 Developer Beta 2 generates an error:
"Installation failed - 0xe8008029 (The code signature is invalid)".

This problem does not occur when signing apps with XCode or iOS App Signer (and then install with XCode).
Looks like the same problem from a few months ago with 14.x beta's and guess it's a simple fix. :) 
Please note: this means everyone updating to iOS 14.5 Developer Beta 2 will see *all* apps installed with AltServer to stop working until they can re-sign their applications with the proper code signature.

**Comment by HiramIII** [comment]
Is there a fix for this?

**Comment by liroyvh** [comment]
> Is there a fix for this?

Not as far as I'm aware. AltStore suffers from the same problem.
