### ISSUE TITLE
Installation of AltStore hangs indefinitely 

### ISSUE THREAD

**Issue by RionDoesThings** [rileytestut/AltServer-Windows#18]
When installing AltStore through AltServer on a wired connection to the PC on windows 10 the installation will hang indefinitely until timing out and network connectivity though all services is impeded until the installation process times out.

**Comment by lonkle** [comment]
**TRY FIRST**
0. Disable Firewall / Antivirus (to rule them out) + try again
1. Log into https://developer.apple.com with your main ID (and agreeing to anything that pops up) + try again
2. Reboot device and laptop / desktop + try again.
3. Make a new Apple ID and use that to try to use AltServer with + try again.
4. Creating a new user on your computer and log into that user and install AltServer, iTunes, iCloud to see if it’s corrupted files on your user login that is cuasing the issue + try again.

**Main Option for your Default Windows User**
1. Uninstall AltServer, iTunes, and iCloud
2. Delete C:/ProgramData/AltServer diretory (can’t think of the actual directory, find an “full” uninstall app for Windows maybe)
3. Reboot
4. Re-install AltServer, iTunes, and iCloud - and install AltStore

**Comment by lonkelle** [comment]
Re-open this if the problem persists after all of the above.

**Comment by RionDoesThings** [comment]
I fixed the issue after reading this however it was not any of the solutions you mentioned and instead a much more confusing one, for some reason my iphone was automatically activating personal hotspot when connected to the PC and the PC was switching to that as its main network whenever altserver attempted to install altstore, deavtivating personal hotspot after connecting the phone to the PC fixed the issue.
