### ISSUE TITLE
Updating libimobiledevice to latest version for Windows Store iTunes support

### ISSUE THREAD

**Issue by chenxiaolong** [rileytestut/AltServer-Windows#3]
Would it be possible to update the bundled libimobiledevice to the latest version?

I tried compiling AltServer against libimobiledevice 1.2.76 from vcpkg (and also libplist 1.2.77, libusbmuxd 1.2.77) and removing the `C:\Program Files (x86)\Common Files\Apple\Mobile Device Support` check. AltServer was able to connect to the Windows Store version of iTunes (`AppleMobileDeviceProcess.exe`) and talk to my device over both USB and Wi-Fi.

~(As a side note, I'm running into [signature verification issues](https://gist.github.com/chenxiaolong/f3e2b651c6c40735b306765e24dbf03e) during the `.ipa` installation, but I haven't figured out if that's due to the libimobiledevice upgrade yet.)~ EDIT: Nevermind. I was just missing `apple.pem` from my build directory and the install process doesn't stop after `SignError` is thrown.

**Comment by xwatermelonx** [comment]
Hey sorry for a late response but mind sharing some build instructions? Thanks mate hope you can do me a favour.

**Comment by xwatermelonx** [comment]
Sir, please respond. 😢

**Comment by Assfugil** [comment]
@chenxiaolong

**Comment by lonkle** [comment]
I believe this is taken care of and build instructions are now on the README of the repo. :)
