### ISSUE TITLE
Instructions about how to compile the solution/projects

### ISSUE THREAD

**Issue by MobilEKG** [rileytestut/AltServer-Windows#5]
Are there any instructions about how to compile the solution/projects?

**Comment by xwatermelonx** [comment]
Same bro I need someone to actually say something..

**Comment by aovestdipaperino** [comment]
I have a resemblance of steps. Any volunteers to make sure that these work? Ping me.

**Comment by xwatermelonx** [comment]
You didn’t include any steps?

**Comment by aovestdipaperino** [comment]
I am in the process of putting them together since there are quite a few quirks and toolset bugs to workaround. I will link them here or ping me.

**Comment by xwatermelonx** [comment]
Feel free to link em.

**Comment by aovestdipaperino** [comment]
https://github.com/rileytestut/AltServer-Windows/pull/6

**Comment by aovestdipaperino** [comment]
Still investigating an issue during install

**Comment by lonkle** [comment]
Thanks to @aovestdipaperino - https://github.com/rileytestut/AltServer-Windows/commit/b7560b2693b27da8a2c560b1bf79f10cf2567ecc
